# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bar',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
